import { NextResponse } from "next/server";

export async function POST(req: Request) {
  try {
    const key = process.env.XAI_API_KEY || "";
    
    if (!key) {
      console.error("Missing XAI_API_KEY");
      return NextResponse.json({ error: "XAI API key is missing" }, { status: 500 });
    }

    const { imageBase64, prompt, format } = await req.json();

    if (!imageBase64) {
      return NextResponse.json({ error: "Reference image (imageBase64) is required" }, { status: 400 });
    }

    const formatContext = format === 'story' 
      ? "Target Format: INSTAGRAM STORY (9:16)."
      : format === 'square'
      ? "Target Format: SQUARE FEED (1:1)."
      : "Target Format: PORTRAIT FEED (4:5).";

    const systemPrompt = `
      You are an elite Art Director and Multimodal AI Designer for "SerenaRaga", a private homecare massage and wellness service in Indonesia.
      Your task is to analyze the provided poster reference image and adapt its art direction, visual mood, color scheme, and typography style for SerenaRaga.
      ${formatContext}
      
      User's Custom Topic / Prompt: "${prompt || 'Promo Spesial Pijat Relaksasi'}"

      Analyze the uploaded image for:
      1. Overall Art Direction, Lighting, Background Subject, and Textures.
      2. Color Palette & Tone (Warm cream, earthy, dark moody, etc.).
      3. Composition & Layout Theme.

      Return the result strictly as a JSON object with these exact fields:
      - theme (MUST BE ONE OF: "split_screen_dark", "classic_glass", "editorial_overlay", "story_minimalist", "solid_poster" based on the uploaded image composition)
      - colorMode (MUST BE "light" or "dark" based on text contrast over background in reference image)
      - label (STRICT Category Tag: "PROMO", "TIPS", "INFO", "QUOTE", "LAYANAN", "TESTIMONI")
      - title (Short, catchy title in Indonesian for SerenaRaga, max 3-4 words)
      - price (Discount/offer if prompt implies promo, e.g. "DISKON 20%", or empty string)
      - description (Concise, engaging body text in Indonesian for SerenaRaga, max 1-2 short sentences)
      - visualSubject (Detailed English description of the background photo/visual to be generated by AI image model, replicating the artistic style, subject matter, lighting, and composition of the reference image, but adapted for spa/wellness. Example: "A serene massage setup with warm candlelight, linen towels, and dried eucalyptus against a textured plaster wall")
      - seasonalNuance (English description of lighting/atmosphere derived from reference image, e.g., "warm golden ambient light, soft cinematic shadows")
      - artStyle (MUST BE "photo" or "vector" based on reference image style)
      - caption (Write in INDONESIAN language. Ready for Instagram. Format with paragraphs, concise hook, body, soft CTA to WhatsApp, max 1-2 natural emojis like 🍃 or 🤍, and hashtags: #SerenaRaga #PijatPanggilanJogja #HomeCareSpa #PijatKeluarga)
    `;

    const imageUrl = imageBase64.startsWith("data:") 
      ? imageBase64 
      : `data:image/jpeg;base64,${imageBase64}`;

    const response = await fetch("https://api.x.ai/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${key}`
      },
      body: JSON.stringify({
        model: "grok-4.3",
        messages: [
          { role: "system", content: systemPrompt },
          {
            role: "user",
            content: [
              { type: "text", text: `Analyze this reference image and adapt its style for SerenaRaga. User prompt: "${prompt || 'Promo Spesial Pijat Relaksasi'}"` },
              { type: "image_url", image_url: { url: imageUrl } }
            ]
          }
        ],
        temperature: 0.7,
        response_format: { type: "json_object" }
      })
    });

    if (!response.ok) {
      const errText = await response.text();
      console.error("Grok Vision API Error:", errText);
      throw new Error(`Grok Vision API Error: ${response.status}`);
    }

    const data = await response.json();
    const content = data.choices[0].message.content;
    const jsonStr = content.replace(/```json|```/g, "").trim();
    const resultJson = JSON.parse(jsonStr);

    return NextResponse.json(resultJson);
  } catch (error: any) {
    console.error("Vision Style API Error Details:", error);
    return NextResponse.json({ 
      error: "Failed to analyze reference style",
      detail: error.message 
    }, { status: 500 });
  }
}
